import React from "react";
import styles from '@/styles/Home.module.css'
import {Header} from "@/Components/Header/Header";
import Image from "next/image";
import Link from "next/link";
import {Inter} from "next/font/google";
import Head from "next/head";
const inter = Inter({ subsets: ['latin'] })



// @ts-ignore
export const MainPage = ({children}) => (
    <div className={styles.main}>
        <Head>
            <title>Server-side rendering</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <main className={styles["center"]}>
            {children}
        </main>
        <nav className={styles.grid}>
            <Link href={"./csr"} className={styles.card}>
                <h2 className={inter.className}>
                    CSR <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    Client Side Rendering
                </p>
            </Link>

            <Link href={"./ssr"} className={styles.card}>
                <h2 className={inter.className}>
                    SSR <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    Server Side Rendering
                </p>
            </Link>

            <Link href={"./ssg"} className={styles.card}>
                <h2 className={inter.className}>
                    SSG <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    Static Site Generator
                </p>
            </Link>

            <Link href={"./isr"} className={styles.card}>
                <h2 className={inter.className}>
                    ISR <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    Incremental Static Regeneration
                </p>
            </Link>
        </nav>
    </div>
);
